# Generated by Django 4.2 on 2023-04-09 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_rating', models.PositiveIntegerField()),
                ('score_value', models.PositiveIntegerField()),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookinnApp.listings')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=150)),
                ('room_type', models.CharField(max_length=150)),
                ('accomodate_count', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('instant_bookable', models.CharField(max_length=150)),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookinnApp.listings')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(max_length=150)),
                ('latitude', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('neighbourhood', models.CharField(max_length=150)),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookinnApp.listings')),
            ],
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', models.CharField(max_length=150)),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookinnApp.listings')),
            ],
        ),
    ]
