# Generated by Django 4.2 on 2023-04-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookinnApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='amenities',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='listings',
            name='name',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='location',
            name='neighbourhood',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='property_details',
            name='property_type',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='property_details',
            name='room_type',
            field=models.TextField(max_length=1500),
        ),
    ]
